### ISSUE TITLE
Talos roadmap

### ISSUE THREAD

**Issue by simonjwinwood** [GaloisInc/daedalus#125]
This is a list of possible future features for Talos.  Each of these will get an issue once we figure out that we want to do it.

### Analysis
- [ ] Field sensitivity for unions
       Currently field sensitivity applies only to records, but we could also use it to have projections over unions.  I am not sure if this will be useful or not.
- [ ] Field sensitivity for arrays
       If we can detect that the body of the array is independent from other iterations, we can potentially synthesise the context of the body once, and then the body multiple times.  For example
```
def Foo = 
  block 
    bound = UInt8
    vs = Many { x = UInt8; x < bount; y = UInt8; y < x } 
    z = UInt 8
    for (v in vs)
       Guard (v.x + v.y < z)
```
where we don't really care about the length of vs

### Strategies
- [ ] Semi-concrete evaluation in the symbolic strategy
       Currently the symbolic strategy sends everything to the solver, but we know the shape of arrays as we construct the through unrolling, so we could avoid some calls to recursive SMT functions by evaluating the Core function on the semi-concrete value.  This would also be useful where we have concrete values in general (e.g. after returning from a labelled Choose1).
- [ ] (Precise) abstract interpretation based strategies
       Some slices, for example 
```
def P = { v = UInt8 # UInt8 # UInt8 # UInt8; Guard (v < 1000) }
```
might be amenable to e.g. interval analysis, esp. when we can invert the expression which constructs the semantic value (as for v above: once we know v, we can determine uniquely the bytes).  If we don't want to backtrack we need a precise analysis, but using something which over-approximates the concrete values may be OK if we backtrack in the strategy which uses the analysis results (and the over-approximation gives a relatively small number of incorrect values)
- [ ] Resurrect the whole-slice symbolic analysis
       This was the original strategy which sent the whole problem to the solver (i.e., used the solver's backtracking to find models, and used the solver to unfold loops etc.).  This was dropped because it was too expensive, but this may have been due to a recently fixed bug in z3 (where get-value looped in the presence of some recursive functions).  This strategy may do better in some cases .

### Architecture
- [ ] Up-front synthesis of slices
       We could generate a number of instances for the slices, and then combine them together later.  This might look like a meta-strategy which precomputes a number of models for the slices, and then picks from them during synthesis time.
- [ ] Parallel strategies
       Currently everything is linear, but we could produce models for slices in parallel, either for the up-front approach, or during synthesis via e.g. promises.
- [ ] More automated strategy choice.
       We could run a number of example slices through the strategies to determine which is likely to work during actual synthesis -- for example, the rand-dfs strategy has a hard time with ```{  x = Numeral; Guard (x == 3) }``` but it may work for other slices, so disabling it for the entire synthesis is non-optimal.  
- [ ] More intentional selection of number of loop iterations.
       Currently we use random path exploration to determine the number of iterations of, for example, a Many, but it is preferable to select the count up-front: for instance, the current method strongly favours fewer counts.
- [ ] User-annotation for inverses
       Some parsers, like Number, have simple-to-write inverses.  Allowing the user to state these (and maybe checking them either through the solver or at least by running some concrete value through) would greatly speed up some synthesis tasks (for example, choosing a number with a given length and bounds currently takes somewhere between 30ms and 200ms depending on the length of the number).  
```
def numberToBytes (n : uint 64) : [UInt8] =
  if n == 0 
  then [] 
  else concat [ [(n mod 10) as uint8 + '0'], numberToBytes (n / 10) ]

@[talos.inverse = numberToBytes]
def Number = ...
```
- [ ] Annotations for distributions of values
       Currently values and branches are chosen uniformly, but it might be useful to have the user (or training data) select a distribution for these choices, and for many bounds as well (i.e., a distribution over the length of the resulting array)
- [ ] Selecting particular code points to target during synthesis
       We would like to ensure good coverage of the DDL spec, and especially for those variables which are included in slices (as they are probably the corner cases we are interested in exploring).  It would be nice for a user (or the system via slice roots) to ensure that certain program points are traversed by the parser for the input generated.
